package javabasics;

public class FakeData {
	
//	Java Faker Class :
//
//		The Java Faker library is commonly used in testing environments for generating realistic fake data.
//
//		Reason to use Java Faker Class in test automation :
//
//		Test Data Generation: Faker simplifies the process of creating test data. Instead of manually creating data for your tests, you can use the Faker library to generate realistic names, addresses, emails, phone numbers,joining date, and many more.
//
//		Data Privacy: In situations where real user data is sensitive and should not be used in test environments, using fake data generated by Faker allows you to respect data privacy.
//
//		Sample Java Code for generating fake data using Faker Class :
	
	/*Maven Dependency :
		<dependency>
		   <groupId>com.github.javafaker</groupId>
		   <artifactId>javafaker</artifactId>
		   <version>1.0.2</version>
		</dependency>*/

//	
	 public static void main(String[] args) {
	      // Create a Faker instance
/*	      Faker faker = new Faker();

	      System.out.println(faker.name().fullName());
	      System.out.println(faker.phoneNumber().cellPhone());
	      System.out.println(faker.address().fullAddress());
	      System.out.println(faker.date().birthday());
	      System.out.println(faker.company().name());

	      System.out.println(faker.name().fullName());
	      System.out.println(faker.phoneNumber().cellPhone());
	      System.out.println(faker.address().fullAddress());
	      System.out.println(faker.date().birthday());
	      System.out.println(faker.company().name());

	      System.out.println(faker.name().fullName());
	      System.out.println(faker.phoneNumber().cellPhone());
	      System.out.println(faker.address().fullAddress());
	      System.out.println(faker.date().birthday());
	      System.out.println(faker.company().name());*/

	   }

}
